# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable version updates for Node
  - package-ecosystem: "node"
    # Look for a `node` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "daily"

   # Enable version updates for Vite
  - package-ecosystem: "vite"
    # Look for a `vite` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "daily"
